### ISSUE TITLE
Help in version 3.0: Trape is yours.

### ISSUE THREAD

**Issue by jofpin** [jofpin/trape#204]
It has been a pleasure for me to contribute to all of you 2 versions of this tool.

I've been working on other open source projects that I'm about to release for you, so I haven't finished trape version 3.0.

But, I invite you and the entire community that has used this project, to collaborate with some lines of code, implementing your own ideas and improving trape, turning it into a project of all, for everyone.

**Comment by Kali95739** [comment]
Trape doesn't work it's always asking for API keys and even when I enter them right it asks for

**Comment by Kali95739** [comment]
Error local variable 'config_trape' referenced before assignment? And asks for the API keys even though there right is this tool broke?

**Comment by Kali95739** [comment]
Can you Help? This script keeps asking for API keys like in a loop? Even though there right? The only thing I can think of is what website should we go to for the IP API key?

**Comment by enty8080** [comment]
1. Ngrok not working
2. Goo.gl not working
There are a lot of work

**Comment by enty8080** [comment]
Sorry, @jofpin , but now your project broken. You must to fix this. A lot of people made issues about the problems, but you don’t want to fix this. Why?

**Comment by MoroLuper** [comment]
**that should fix the Error local variable 'config_trape' referenced before assignment**
in core/trape.py
_find:_
`v = '{\n\t"ngrok_token" : "' + c_nGrokToken + '",\n\t"gmaps_api_key" : "' + c_gMapsToken + '",\n\t"gshortener_api_key" : "' + c_gOoglToken + '"\n\t"ipinfo_api_key" : "' + c_ipinfo + '",\n}'
`
_replace with:_
`v = '{\n\t"ngrok_token" : "' + c_nGrokToken + '",\n\t"gmaps_api_key" : "' + c_gMapsToken + '",\n\t"gshortener_api_key" : "' + c_gOoglToken + '",\n\t"ipinfo_api_key" : "' + c_ipinfo + '"\n}'`

**Comment by enty8080** [comment]
Why ngrok is not working?

**Comment by Blacksorceres** [comment]
no funciona @MoroLuper

**Comment by Kali95739** [comment]
This tool is dead apparently??

**Comment by websmartfeedback** [comment]
> v = '{\n\t"ngrok_token" : "' + c_nGrokToken + '",\n\t"gmaps_api_key" : "' + c_gMapsToken + '",\n\t"gshortener_api_key" : "' + c_gOoglToken + '",\n\t"ipinfo_api_key" : "' + c_ipinfo + '"\n}'

Not Working, Can you please explain

Thanks

**Comment by jonodrew** [comment]
First things first - let's get it working on python3.

**Comment by AWALmdAWAL** [comment]
Help me pleas??

**Comment by AWALmdAWAL** [comment]
Can you help me??

**Comment by kaylasantos885** [comment]
3.0 will done this year?

**Comment by hwac121** [comment]
HEY IDIOTS!!! Pay attention, the man is telling you he can no longer work on this project and is basically looking for someone to take it over...or others to take it over. Stop complaining if you have a problem and just fix it then add your new code to the rep.

**Comment by kaylasantos885** [comment]
hwac121, you mother also said can no longer fuck but every day call me. so go way

**Comment by kaylasantos885** [comment]
> 
> 
> HEY IDIOTS!!! Pay attention, the man is telling you he can no longer work on this project and is basically looking for someone to take it over...or others to take it over. Stop complaining if you have a problem and just fix it then add your new code to the rep.

hwac121, you mother also said can no longer fuck but every day call me. so go way

**Comment by hwac121** [comment]
> > HEY IDIOTS!!! Pay attention, the man is telling you he can no longer work on this project and is basically looking for someone to take it over...or others to take it over. Stop complaining if you have a problem and just fix it then add your new code to the rep.
> 
> hwac121, you mother also said can no longer fuck but every day call me. so go way

Oh thanks Kaylasantos885, now I don't have to point out the idiots since you pointed yourself out like that. Funny the way people talk shit they would never say face to face. We know, you are just trying to compensate for a little...well you know....so we all understand you lashing out Kayla. Kayla, isn't that a female's name?

**Comment by DSRobin** [comment]
> > HEY IDIOTS!!! Pay attention, the man is telling you he can no longer work on this project and is basically looking for someone to take it over...or others to take it over. Stop complaining if you have a problem and just fix it then add your new code to the rep.
> 
> hwac121, you mother also said can no longer fuck but every day call me. so go way

You are a jerk, please find another place to troll around.

**Comment by ale-big** [comment]
> It has been a pleasure for me to contribute to all of you 2 versions of this tool.
> 
> I've been working on other open source projects that I'm about to release for you, so I haven't finished trape version 3.0.
> 
> But, I invite you and the entire community that has used this project, to collaborate with some lines of code, implementing your own ideas and improving trape, turning it into a project of all, for everyone.

Hi, there is a repository for version 3.0 ?

**Comment by abdullzz** [comment]
> First things first - let's get it working on python3.
put this as the highest priority. since python 2 is outdated

**Comment by NLPoker** [comment]
After hearing about Trape for the first time 4 days ago and literally NEVER done ANYTHING with Python, I was able to get Trape installed and operational! This version still works... you just have to do some research and, frankly, quickly learn basic Python. If I can do it then you can do it!

**Comment by ultra99spec** [comment]
@NLPoker  Yo man
How did you get it working, I followed everything from the how to install section (including virtual 2.7), installed flask socket <5.0.0.
And followed the #277 error "cannot import name JSONDecodeError"
"And the temporary fix to this issue to run pip install simplejson and go to the C:\....\python27\Lib\site-packages\engineio\client.py file and change the from json import JSONDecodeError to from simplejson import JSONDecodeError. I tried it but in my 2.7 directory (using Kali Linux) I could't find the line "from json import JSONDecodeError". I did find that line in the 3.9 directory of python (so the client.py file same same as the 2.7) What I than did was add the line "from simplejson import JSONDecodeError" at the same spot in the 2.7 client.py as in the 3.9 client.py.

Still getting the "cannot import name JSONDecodeError" error. :/ Tried looking for the module in the code but can't find it. How did you get it working?

**Comment by NLPoker** [comment]
@ultra99spec I found the client.py file! I was using PYENV to manage my environment so I had to check there. Once I did that and modified the line as suggested it worked.

**Comment by ultra99spec** [comment]
@NLPoker So the line "from json import JSONDecodeError" was allready in the client.py file where you were looking?
Where was it located on your environment? the location stated above or somewhere else?
And which python version are you using? Maybe that could be why I can't get it working.
Thanks for the quick response btw!

**Comment by NLPoker** [comment]
@ultra99spec Mine was in a similar location but not exact. Frankly I don’t have that computer with me so I can’t get the exact path. 

Yes, that line was already in the client.py file. You may also want to try searching for that line specifically to see if your computer can identify it within a file.

I got it working on v2.7.18

**Comment by ultra99spec** [comment]
@NLPoker Than ill try that!
Maybe I also need to do a clean install. It was actually working quite well for me for 6 months or so
But today I updated Kali from 19.xx to 20.xx and python etc too.
It suddenly stopped working :/ Feels bad
In the client.py file I searched for the line in nano but to to avail.
Thanks again for the response !
